// <auto-generated />
using System;
using MAS_Końcowy.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MAS_Końcowy.Migrations
{
    [DbContext(typeof(MASContext))]
    [Migration("20200620171409_fixedAddressPerson")]
    partial class fixedAddressPerson
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MAS_Końcowy.Model.Address", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("BuildingNumber")
                        .HasColumnType("text");

                    b.Property<string>("CityName")
                        .HasColumnType("text");

                    b.Property<string>("FlatNumber")
                        .HasColumnType("text");

                    b.Property<string>("Postcode")
                        .HasColumnType("text");

                    b.Property<string>("StreetName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("MAS_Końcowy.Model.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateOfSigning")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("NumberOfDeliveries")
                        .HasColumnType("integer");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("MAS_Końcowy.Model.ContractIngredient", b =>
                {
                    b.Property<int>("ContractId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.HasKey("ContractId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("ContractIngredient");
                });

            modelBuilder.Entity("MAS_Końcowy.Model.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AnimalOrigin")
                        .HasColumnType("integer");

                    b.Property<bool>("GlutenFree")
                        .HasColumnType("boolean");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("MAS_Końcowy.Model.DishContent", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.HasKey("DishId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("DishContents");
                });

            modelBuilder.Entity("MAS_Końcowy.Model.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("PricePerKg")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("MAS_Końcowy.Model.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("ProfitMargin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("MAS_Końcowy.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CookId")
                        .HasColumnType("integer");

                    b.Property<int?>("DelivererId")
                        .HasColumnType("integer");

                    b.Property<int?>("DeliveryAddressId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int?>("TableNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("WaiterId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CookId");

                    b.HasIndex("DelivererId");

                    b.HasIndex("DeliveryAddressId");

                    b.HasIndex("WaiterId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MAS_Końcowy.Model.OrderContent", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<double>("Number")
                        .HasColumnType("double precision");

                    b.HasKey("DishId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderContent");
                });

            modelBuilder.Entity("MAS_Końcowy.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("MAS_Końcowy.Model.Cook", b =>
                {
                    b.HasBaseType("MAS_Końcowy.Model.Person");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PESEL")
                        .HasColumnType("text");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("SanepidBookExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasDiscriminator().HasValue("Cook");
                });

            modelBuilder.Entity("MAS_Końcowy.Model.Deliverer", b =>
                {
                    b.HasBaseType("MAS_Końcowy.Model.Person");

                    b.Property<string>("DrivingLicense")
                        .HasColumnType("text");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PESEL")
                        .HasColumnType("text");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("SanepidBookExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasDiscriminator().HasValue("Deliverer");
                });

            modelBuilder.Entity("MAS_Końcowy.Model.IngredientsSupplier", b =>
                {
                    b.HasBaseType("MAS_Końcowy.Model.Person");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<bool>("HasRefrigeratedTrailers")
                        .HasColumnType("boolean");

                    b.Property<string>("NIP")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("IngredientsSupplier");
                });

            modelBuilder.Entity("MAS_Końcowy.Model.Manager", b =>
                {
                    b.HasBaseType("MAS_Końcowy.Model.Person");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PESEL")
                        .HasColumnType("text");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("SanepidBookExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasDiscriminator().HasValue("Manager");
                });

            modelBuilder.Entity("MAS_Końcowy.Model.Waiter", b =>
                {
                    b.HasBaseType("MAS_Końcowy.Model.Person");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PESEL")
                        .HasColumnType("text");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("SanepidBookExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasDiscriminator().HasValue("Waiter");
                });

            modelBuilder.Entity("MAS_Końcowy.Model.Address", b =>
                {
                    b.HasOne("MAS_Końcowy.Model.Person", "Person")
                        .WithOne("Address")
                        .HasForeignKey("MAS_Końcowy.Model.Address", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAS_Końcowy.Model.Contract", b =>
                {
                    b.HasOne("MAS_Końcowy.Model.IngredientsSupplier", "Supplier")
                        .WithMany("Contracts")
                        .HasForeignKey("SupplierId");
                });

            modelBuilder.Entity("MAS_Końcowy.Model.ContractIngredient", b =>
                {
                    b.HasOne("MAS_Końcowy.Model.Contract", "Contract")
                        .WithMany("ContractIngredients")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAS_Końcowy.Model.Ingredient", "Ingredient")
                        .WithMany("ContractIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAS_Końcowy.Model.Dish", b =>
                {
                    b.HasOne("MAS_Końcowy.Model.Menu", "Menu")
                        .WithMany("Dishes")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAS_Końcowy.Model.DishContent", b =>
                {
                    b.HasOne("MAS_Końcowy.Model.Dish", "Dish")
                        .WithMany("DishIngredients")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAS_Końcowy.Model.Ingredient", "Ingredient")
                        .WithMany("DishContents")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAS_Końcowy.Model.Order", b =>
                {
                    b.HasOne("MAS_Końcowy.Model.Cook", "Cook")
                        .WithMany("CookedOrders")
                        .HasForeignKey("CookId");

                    b.HasOne("MAS_Końcowy.Model.Deliverer", "Deliverer")
                        .WithMany("DeliveredOrders")
                        .HasForeignKey("DelivererId");

                    b.HasOne("MAS_Końcowy.Model.Address", "DeliveryAddress")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MAS_Końcowy.Model.Waiter", "Waiter")
                        .WithMany("HandledOrders")
                        .HasForeignKey("WaiterId");
                });

            modelBuilder.Entity("MAS_Końcowy.Model.OrderContent", b =>
                {
                    b.HasOne("MAS_Końcowy.Model.Dish", "Dish")
                        .WithMany("OrderContents")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAS_Końcowy.Model.Order", "Order")
                        .WithMany("OrderContents")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
